"""Convert common LaTeX-like commands to Word UnicodeMath text."""

import re

_UNICODE_MATH = {
    # Greek lowercase
    r"\alpha": "\u03b1",
    r"\beta": "\u03b2",
    r"\gamma": "\u03b3",
    r"\delta": "\u03b4",
    r"\epsilon": "\u03b5",
    r"\varepsilon": "\u03b5",
    r"\zeta": "\u03b6",
    r"\eta": "\u03b7",
    r"\theta": "\u03b8",
    r"\vartheta": "\u03d1",
    r"\iota": "\u03b9",
    r"\kappa": "\u03ba",
    r"\lambda": "\u03bb",
    r"\mu": "\u03bc",
    r"\nu": "\u03bd",
    r"\xi": "\u03be",
    r"\pi": "\u03c0",
    r"\rho": "\u03c1",
    r"\sigma": "\u03c3",
    r"\varsigma": "\u03c2",
    r"\tau": "\u03c4",
    r"\upsilon": "\u03c5",
    r"\phi": "\u03c6",
    r"\varphi": "\u03d5",
    r"\chi": "\u03c7",
    r"\psi": "\u03c8",
    r"\omega": "\u03c9",
    # Greek uppercase
    r"\Gamma": "\u0393",
    r"\Delta": "\u0394",
    r"\Theta": "\u0398",
    r"\Lambda": "\u039b",
    r"\Xi": "\u039e",
    r"\Pi": "\u03a0",
    r"\Sigma": "\u03a3",
    r"\Upsilon": "\u03a5",
    r"\Phi": "\u03a6",
    r"\Psi": "\u03a8",
    r"\Omega": "\u03a9",
    # Operators / big operators
    r"\int": "\u222b",
    r"\iint": "\u222c",
    r"\iiint": "\u222d",
    r"\oint": "\u222e",
    r"\sum": "\u2211",
    r"\prod": "\u220f",
    r"\coprod": "\u2210",
    # Roots and radicals
    r"\sqrt": "\u221a",
    r"\cbrt": "\u221b",
    # Calculus / analysis
    r"\partial": "\u2202",
    r"\nabla": "\u2207",
    r"\infty": "\u221e",
    # Logic / set theory
    r"\forall": "\u2200",
    r"\exists": "\u2203",
    r"\nexists": "\u2204",
    r"\in": "\u2208",
    r"\notin": "\u2209",
    r"\subset": "\u2282",
    r"\supset": "\u2283",
    r"\subseteq": "\u2286",
    r"\supseteq": "\u2287",
    r"\cup": "\u222a",
    r"\cap": "\u2229",
    r"\emptyset": "\u2205",
    r"\neg": "\u00ac",
    r"\land": "\u2227",
    r"\lor": "\u2228",
    # Arithmetic / relations
    r"\pm": "\u00b1",
    r"\mp": "\u2213",
    r"\times": "\u00d7",
    r"\div": "\u00f7",
    r"\cdot": "\u22c5",
    r"\leq": "\u2264",
    r"\geq": "\u2265",
    r"\neq": "\u2260",
    r"\approx": "\u2248",
    r"\equiv": "\u2261",
    r"\cong": "\u2245",
    r"\sim": "\u223c",
    r"\propto": "\u221d",
    r"\ll": "\u226a",
    r"\gg": "\u226b",
    # Arrows
    r"\rightarrow": "\u2192",
    r"\leftarrow": "\u2190",
    r"\leftrightarrow": "\u2194",
    r"\Rightarrow": "\u21d2",
    r"\Leftarrow": "\u21d0",
    r"\Leftrightarrow": "\u21d4",
    r"\uparrow": "\u2191",
    r"\downarrow": "\u2193",
    r"\mapsto": "\u21a6",
    # Dots
    r"\cdots": "\u22ef",
    r"\ldots": "\u2026",
    r"\vdots": "\u22ee",
    r"\ddots": "\u22f1",
    # Miscellaneous
    r"\angle": "\u2220",
    r"\degree": "\u00b0",
    r"\star": "\u22c6",
    r"\circ": "\u2218",
    r"\bullet": "\u2022",
    r"\diamond": "\u22c4",
    r"\triangle": "\u25b3",
    r"\hbar": "\u210f",
    r"\ell": "\u2113",
    r"\Re": "\u211c",
    r"\Im": "\u2124",
    r"\aleph": "\u2135",
    # Matrix (Word UnicodeMath uses ■ for matrix)
    r"\matrix": "\u25a0",
    r"\pmatrix": "\u25a0",
    # Function names (these stay as text but without backslash)
    r"\lim": "lim",
    r"\sin": "sin",
    r"\cos": "cos",
    r"\tan": "tan",
    r"\sec": "sec",
    r"\csc": "csc",
    r"\cot": "cot",
    r"\arcsin": "arcsin",
    r"\arccos": "arccos",
    r"\arctan": "arctan",
    r"\sinh": "sinh",
    r"\cosh": "cosh",
    r"\tanh": "tanh",
    r"\log": "log",
    r"\ln": "ln",
    r"\exp": "exp",
    r"\det": "det",
    r"\dim": "dim",
    r"\ker": "ker",
    r"\min": "min",
    r"\max": "max",
    r"\inf": "inf",
    r"\sup": "sup",
    r"\gcd": "gcd",
    r"\arg": "arg",
    r"\mod": "mod",
}


def to_unicode_math(equation: str) -> str:
    """Convert supported commands without partially matching longer names."""
    commands = sorted(_UNICODE_MATH, key=len, reverse=True)
    pattern = "|".join(re.escape(command) for command in commands)
    pattern = f"({pattern})(?![a-zA-Z])"
    return re.sub(pattern, lambda match: _UNICODE_MATH[match.group(1)], equation)
